# Curated Local Database of Common Foods (values per 100g / 100ml unless serving_weight is used for pieces)
COMMON_FOODS = {
    "chicken breast": {
        "name": "Chicken Breast",
        "synonyms": ["chicken breast", "chicken breasts", "chicken", "cooked chicken breast"],
        "calories": 165,
        "protein_g": 31.0,
        "carbs_g": 0.0,
        "fat_g": 3.6,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 15.0,
        "iron_mg": 1.0
    },
    "egg": {
        "name": "Egg",
        "synonyms": ["egg", "eggs", "boiled egg", "scrambled egg", "fried egg", "whole egg"],
        "serving_weight": 50.0,  # weight of one large egg in grams
        "calories": 155,        # per 100g
        "protein_g": 12.6,
        "carbs_g": 1.1,
        "fat_g": 10.6,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 56.0,
        "iron_mg": 1.8
    },
    "banana": {
        "name": "Banana",
        "synonyms": ["banana", "bananas"],
        "serving_weight": 118.0,
        "calories": 89,
        "protein_g": 1.1,
        "carbs_g": 22.8,
        "fat_g": 0.3,
        "vitamin_c_mg": 8.7,
        "calcium_mg": 5.0,
        "iron_mg": 0.3
    },
    "apple": {
        "name": "Apple",
        "synonyms": ["apple", "apples", "red apple", "green apple"],
        "serving_weight": 182.0,
        "calories": 52,
        "protein_g": 0.3,
        "carbs_g": 13.8,
        "fat_g": 0.2,
        "vitamin_c_mg": 4.6,
        "calcium_mg": 6.0,
        "iron_mg": 0.1
    },
    "white rice": {
        "name": "White Rice",
        "synonyms": ["white rice", "rice", "cooked white rice", "cooked rice"],
        "calories": 130,  # per 100g cooked
        "protein_g": 2.7,
        "carbs_g": 28.0,
        "fat_g": 0.3,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 10.0,
        "iron_mg": 0.2
    },
    "brown rice": {
        "name": "Brown Rice",
        "synonyms": ["brown rice", "cooked brown rice"],
        "calories": 111,  # per 100g cooked
        "protein_g": 2.6,
        "carbs_g": 23.0,
        "fat_g": 0.9,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 10.0,
        "iron_mg": 0.4
    },
    "oats": {
        "name": "Oats",
        "synonyms": ["oats", "oatmeal", "rolled oats"],
        "calories": 389,  # per 100g dry
        "protein_g": 16.9,
        "carbs_g": 66.3,
        "fat_g": 6.9,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 54.0,
        "iron_mg": 4.7
    },
    "milk": {
        "name": "Whole Milk",
        "synonyms": ["milk", "whole milk", "cow milk", "glass of milk"],
        "calories": 61,
        "protein_g": 3.2,
        "carbs_g": 4.8,
        "fat_g": 3.3,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 113.0,
        "iron_mg": 0.0
    },
    "broccoli": {
        "name": "Broccoli",
        "synonyms": ["broccoli", "cooked broccoli", "raw broccoli"],
        "calories": 34,
        "protein_g": 2.8,
        "carbs_g": 7.0,
        "fat_g": 0.4,
        "vitamin_c_mg": 89.2,
        "calcium_mg": 47.0,
        "iron_mg": 0.7
    },
    "salmon": {
        "name": "Salmon",
        "synonyms": ["salmon", "salmon fillet", "cooked salmon", "grilled salmon"],
        "calories": 208,
        "protein_g": 20.0,
        "carbs_g": 0.0,
        "fat_g": 13.0,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 9.0,
        "iron_mg": 0.3
    },
    "beef": {
        "name": "Beef",
        "synonyms": ["beef", "cooked beef", "steak", "ground beef"],
        "calories": 250,
        "protein_g": 26.0,
        "carbs_g": 0.0,
        "fat_g": 15.0,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 18.0,
        "iron_mg": 2.6
    },
    "potato": {
        "name": "Potato",
        "synonyms": ["potato", "potatoes", "boiled potato", "baked potato"],
        "calories": 87,
        "protein_g": 1.9,
        "carbs_g": 20.1,
        "fat_g": 0.1,
        "vitamin_c_mg": 13.0,
        "calcium_mg": 5.0,
        "iron_mg": 0.3
    },
    "sweet potato": {
        "name": "Sweet Potato",
        "synonyms": ["sweet potato", "sweet potatoes", "baked sweet potato"],
        "calories": 86,
        "protein_g": 1.6,
        "carbs_g": 20.1,
        "fat_g": 0.1,
        "vitamin_c_mg": 2.4,
        "calcium_mg": 30.0,
        "iron_mg": 0.6
    },
    "avocado": {
        "name": "Avocado",
        "synonyms": ["avocado", "avocados"],
        "serving_weight": 150.0,
        "calories": 160,
        "protein_g": 2.0,
        "carbs_g": 8.5,
        "fat_g": 14.7,
        "vitamin_c_mg": 10.0,
        "calcium_mg": 12.0,
        "iron_mg": 0.6
    },
    "kare kare": {
        "name": "Kare Kare",
        "synonyms": ["kare kare", "kare-kare", "beef kare kare", "pork kare kare"],
        "serving_weight": 200.0,
        "calories": 310,
        "protein_g": 22.0,
        "carbs_g": 11.0,
        "fat_g": 20.0,
        "vitamin_c_mg": 4.0,
        "calcium_mg": 45.0,
        "iron_mg": 2.2
    },
    "adobong baboy": {
        "name": "Adobong Baboy",
        "synonyms": ["adobong baboy", "pork adobo", "adobo baboy"],
        "serving_weight": 180.0,
        "calories": 340,
        "protein_g": 24.0,
        "carbs_g": 5.0,
        "fat_g": 25.0,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 20.0,
        "iron_mg": 1.8
    },
    "chicken adobo": {
        "name": "Chicken Adobo",
        "synonyms": ["chicken adobo", "adobong manok", "adobo manok"],
        "serving_weight": 180.0,
        "calories": 290,
        "protein_g": 28.0,
        "carbs_g": 4.0,
        "fat_g": 17.0,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 18.0,
        "iron_mg": 1.5
    },
    "pork sinigang": {
        "name": "Pork Sinigang",
        "synonyms": ["pork sinigang", "sinigang na baboy", "sinigang baboy"],
        "serving_weight": 250.0,
        "calories": 320,
        "protein_g": 22.0,
        "carbs_g": 10.0,
        "fat_g": 21.0,
        "vitamin_c_mg": 15.0,
        "calcium_mg": 35.0,
        "iron_mg": 2.0
    },
    "pork sisig": {
        "name": "Pork Sisig",
        "synonyms": ["pork sisig", "sisig", "sizzling sisig"],
        "serving_weight": 150.0,
        "calories": 390,
        "protein_g": 21.0,
        "carbs_g": 6.0,
        "fat_g": 31.0,
        "vitamin_c_mg": 5.0,
        "calcium_mg": 25.0,
        "iron_mg": 2.1
    },
    "crispy pata": {
        "name": "Crispy Pata",
        "synonyms": ["crispy pata", "pata"],
        "serving_weight": 200.0,
        "calories": 480,
        "protein_g": 32.0,
        "carbs_g": 2.0,
        "fat_g": 38.0,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 20.0,
        "iron_mg": 2.5
    },
    "bicol express": {
        "name": "Bicol Express",
        "synonyms": ["bicol express"],
        "serving_weight": 180.0,
        "calories": 360,
        "protein_g": 19.0,
        "carbs_g": 7.0,
        "fat_g": 29.0,
        "vitamin_c_mg": 12.0,
        "calcium_mg": 30.0,
        "iron_mg": 1.9
    },
    "lechon kawali": {
        "name": "Lechon Kawali",
        "synonyms": ["lechon kawali", "crispy pork belly"],
        "serving_weight": 150.0,
        "calories": 420,
        "protein_g": 22.0,
        "carbs_g": 1.0,
        "fat_g": 36.0,
        "vitamin_c_mg": 0.0,
        "calcium_mg": 15.0,
        "iron_mg": 1.6
    },
    "pork menudo": {
        "name": "Pork Menudo",
        "synonyms": ["pork menudo", "menudo"],
        "serving_weight": 200.0,
        "calories": 310,
        "protein_g": 23.0,
        "carbs_g": 14.0,
        "fat_g": 18.0,
        "vitamin_c_mg": 18.0,
        "calcium_mg": 28.0,
        "iron_mg": 2.8
    },
    "dinuguan": {
        "name": "Dinuguan",
        "synonyms": ["dinuguan", "pork blood stew"],
        "serving_weight": 200.0,
        "calories": 260,
        "protein_g": 25.0,
        "carbs_g": 6.0,
        "fat_g": 15.0,
        "vitamin_c_mg": 3.0,
        "calcium_mg": 22.0,
        "iron_mg": 18.0
    },
    "bulalo": {
        "name": "Bulalo",
        "synonyms": ["bulalo", "beef bulalo"],
        "serving_weight": 300.0,
        "calories": 410,
        "protein_g": 35.0,
        "carbs_g": 8.0,
        "fat_g": 26.0,
        "vitamin_c_mg": 6.0,
        "calcium_mg": 40.0,
        "iron_mg": 3.5
    },
    "beef caldereta": {
        "name": "Beef Caldereta",
        "synonyms": ["beef caldereta", "caldereta"],
        "serving_weight": 220.0,
        "calories": 370,
        "protein_g": 28.0,
        "carbs_g": 16.0,
        "fat_g": 21.0,
        "vitamin_c_mg": 15.0,
        "calcium_mg": 32.0,
        "iron_mg": 3.2
    },
    "bistek tagalog": {
        "name": "Bistek Tagalog",
        "synonyms": ["bistek tagalog", "bistek", "beef steak"],
        "serving_weight": 180.0,
        "calories": 310,
        "protein_g": 30.0,
        "carbs_g": 8.0,
        "fat_g": 17.0,
        "vitamin_c_mg": 8.0,
        "calcium_mg": 22.0,
        "iron_mg": 3.0
    },
    "beef pares": {
        "name": "Beef Pares",
        "synonyms": ["beef pares", "pares"],
        "serving_weight": 200.0,
        "calories": 350,
        "protein_g": 27.0,
        "carbs_g": 20.0,
        "fat_g": 18.0,
        "vitamin_c_mg": 2.0,
        "calcium_mg": 25.0,
        "iron_mg": 2.8
    },
    "pork tocino": {
        "name": "Pork Tocino",
        "synonyms": ["pork tocino", "tocino"],
        "serving_weight": 120.0,
        "calories": 320,
        "protein_g": 18.0,
        "carbs_g": 16.0,
        "fat_g": 20.0,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 15.0,
        "iron_mg": 1.2
    },
    "lumpia shanghai": {
        "name": "Lumpia Shanghai",
        "synonyms": ["lumpia shanghai", "lumpiang shanghai", "lumpia"],
        "serving_weight": 100.0,
        "calories": 280,
        "protein_g": 12.0,
        "carbs_g": 18.0,
        "fat_g": 17.0,
        "vitamin_c_mg": 2.0,
        "calcium_mg": 20.0,
        "iron_mg": 1.4
    },
    "tapsilog": {
        "name": "Tapsilog",
        "synonyms": ["tapsilog"],
        "serving_weight": 280.0,
        "calories": 540,
        "protein_g": 28.0,
        "carbs_g": 48.0,
        "fat_g": 25.0,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 65.0,
        "iron_mg": 3.8
    },
    "tocilog": {
        "name": "Tocilog",
        "synonyms": ["tocilog"],
        "serving_weight": 280.0,
        "calories": 570,
        "protein_g": 24.0,
        "carbs_g": 54.0,
        "fat_g": 28.0,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 60.0,
        "iron_mg": 2.8
    },
    "longsilog": {
        "name": "Longsilog",
        "synonyms": ["longsilog"],
        "serving_weight": 280.0,
        "calories": 590,
        "protein_g": 22.0,
        "carbs_g": 52.0,
        "fat_g": 32.0,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 58.0,
        "iron_mg": 2.6
    },
    "bangsilog": {
        "name": "Bangsilog",
        "synonyms": ["bangsilog"],
        "serving_weight": 280.0,
        "calories": 480,
        "protein_g": 30.0,
        "carbs_g": 46.0,
        "fat_g": 19.0,
        "vitamin_c_mg": 2.0,
        "calcium_mg": 85.0,
        "iron_mg": 2.9
    },
    "sinangag": {
        "name": "Sinangag",
        "synonyms": ["sinangag", "garlic fried rice", "garlic rice"],
        "serving_weight": 150.0,
        "calories": 230,
        "protein_g": 4.5,
        "carbs_g": 44.0,
        "fat_g": 4.2,
        "vitamin_c_mg": 1.0,
        "calcium_mg": 18.0,
        "iron_mg": 0.8
    },
    "pancit canton": {
        "name": "Pancit Canton",
        "synonyms": ["pancit canton"],
        "serving_weight": 200.0,
        "calories": 380,
        "protein_g": 14.0,
        "carbs_g": 52.0,
        "fat_g": 13.0,
        "vitamin_c_mg": 8.0,
        "calcium_mg": 40.0,
        "iron_mg": 2.2
    },
    "pancit bihon": {
        "name": "Pancit Bihon",
        "synonyms": ["pancit bihon"],
        "serving_weight": 200.0,
        "calories": 310,
        "protein_g": 12.0,
        "carbs_g": 46.0,
        "fat_g": 9.0,
        "vitamin_c_mg": 7.0,
        "calcium_mg": 35.0,
        "iron_mg": 1.8
    },
    "pancit palabok": {
        "name": "Pancit Palabok",
        "synonyms": ["pancit palabok", "palabok"],
        "serving_weight": 220.0,
        "calories": 360,
        "protein_g": 15.0,
        "carbs_g": 48.0,
        "fat_g": 12.0,
        "vitamin_c_mg": 5.0,
        "calcium_mg": 60.0,
        "iron_mg": 2.4
    },
    "pancit malabon": {
        "name": "Pancit Malabon",
        "synonyms": ["pancit malabon"],
        "serving_weight": 220.0,
        "calories": 390,
        "protein_g": 17.0,
        "carbs_g": 50.0,
        "fat_g": 14.0,
        "vitamin_c_mg": 6.0,
        "calcium_mg": 70.0,
        "iron_mg": 2.6
    },
    "halo halo": {
        "name": "Halo Halo",
        "synonyms": ["halo halo", "halo-halo"],
        "serving_weight": 300.0,
        "calories": 350,
        "protein_g": 6.0,
        "carbs_g": 68.0,
        "fat_g": 7.0,
        "vitamin_c_mg": 12.0,
        "calcium_mg": 180.0,
        "iron_mg": 1.2
    },
    "tortang talong": {
        "name": "Tortang Talong",
        "synonyms": ["tortang talong", "eggplant omelet"],
        "serving_weight": 180.0,
        "calories": 210,
        "protein_g": 9.0,
        "carbs_g": 12.0,
        "fat_g": 14.0,
        "vitamin_c_mg": 10.0,
        "calcium_mg": 40.0,
        "iron_mg": 1.6
    },
    "pinakbet": {
        "name": "Pinakbet",
        "synonyms": ["pinakbet", "pakbet"],
        "serving_weight": 200.0,
        "calories": 160,
        "protein_g": 7.0,
        "carbs_g": 18.0,
        "fat_g": 7.0,
        "vitamin_c_mg": 25.0,
        "calcium_mg": 55.0,
        "iron_mg": 2.0
    },
    "laing": {
        "name": "Laing",
        "synonyms": ["laing"],
        "serving_weight": 150.0,
        "calories": 240,
        "protein_g": 6.0,
        "carbs_g": 12.0,
        "fat_g": 19.0,
        "vitamin_c_mg": 18.0,
        "calcium_mg": 90.0,
        "iron_mg": 2.4
    }
}

